# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for android-agent standalone exe."""

import sys
from pathlib import Path

HERE = Path(SPECPATH)

a = Analysis(
    [str(HERE / "src" / "agent" / "main.py")],
    pathex=[str(HERE / "src")],
    binaries=[],
    datas=[
        (str(HERE / "src" / "agent" / "ui" / "static" / "index.html"), "agent/ui/static"),
        (str(HERE / "src" / "agent" / "config" / "default.yaml"), "agent/config"),
    ],
    hiddenimports=[
        "agent",
        "agent.core",
        "agent.core.loop",
        "agent.core.state",
        "agent.core.context",
        "agent.core.planner",
        "agent.llm",
        "agent.llm.client",
        "agent.llm.parser",
        "agent.llm.prompts",
        "agent.llm.tools",
        "agent.device",
        "agent.device.bridge",
        "agent.device.executor",
        "agent.device.protocol",
        "agent.config",
        "agent.config.config",
        "agent.speech",
        "agent.speech.transcriber",
        "agent.speech.tts",
        "agent.speech.vad",
        "agent.nlu",
        "agent.nlu.app_mapper",
        "agent.nlu.screen_recognizer",
        "agent.nlu.entity_extractor",
        "agent.ui",
        "agent.ui.cli",
        "agent.ui.config",
        "agent.ui.web_server",
        "agent.device.discovery",
        "agent.device.adb",
        "zeroconf",
        "zeroconf._utils",
        "zeroconf._services",
        "zeroconf._dns",
        "ifaddr",
        "pydantic",
        "pydantic_settings",
        "yaml",
        "websockets",
        "openai",
        "uvicorn",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "websockets.asyncio",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "PIL",
        "cv2",
        "scipy",
        "torch",
        "tensorflow",
        "pandas",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="android-agent",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="android-agent",
)
